apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: headway-volume
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 50Mi
      initContainers:
        - name: init
          image: ghcr.io/headwaymaps/headway-init:maps-earth-dev
          imagePullPolicy: Always
          volumeMounts:
            - name: headway-volume
              mountPath: /data
          env:
            - name: HEADWAY_BBOX
              value: ""
            - name: HEADWAY_ENABLE_TRANSIT_ROUTING
              value: "1"
            - name: HEADWAY_ABOUT_URL
              value: "https://about.maps.earth"
            - name: HEADWAY_ABOUT_LINK_TEXT
              value: "About maps.earth"
            - name: HEADWAY_CONTACT_URL
              value: "mailto:info@maps.earth?subject=Hello,%20Earth"
            - name: HEADWAY_CONTACT_LINK_TEXT
              value: "Contact Us"
          resources:
            limits:
              memory: 100Mi
            requests:
              memory: 100Mi
      containers:
        - name: main
          image: ghcr.io/headwaymaps/headway:maps-earth-dev
          imagePullPolicy: Always
          volumeMounts:
            - name: headway-volume
              mountPath: /data
          ports:
            - containerPort: 8080
          env:
            - name: HEADWAY_TILESERVER_URL
              value: http://tileserver:8000
            - name: HEADWAY_PELIAS_URL
              value: http://pelias-api:4000
            - name: HEADWAY_PUBLIC_URL
              value: "https://maps.earth"
            - name: HEADWAY_ENABLE_TRANSIT_ROUTING
              value: "1"
          resources:
            limits:
              memory: 300Mi
            requests:
              memory: 100Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
