apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentripplanner-los-angeles-maps-earth-planet-v1-260817-0-13-0-2026-09-17-0fc87d07
  labels:
    app.kubernetes.io/part-of: headway
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
