#!/bin/sh
#
# Run formatting and linting checks.
#
# The checks should align with our CI checks in .github/workflows/frontend-checks.yml
#
# To automatically run before each commit, copy or symlink this into .git/hooks/
#
# You can commit without running the checks by running `git commit --no-verify` if need be.

set -e

(cd web/frontend &&
  yarn format &&
  yarn lint &&
  yarn tsc)

(cd services/transitmux &&
    cargo fmt &&
    cargo clippy -- -D warnings &&
    cargo test)
