apiVersion: v1
kind: ConfigMap
metadata:
  name: otp-losangeles-config
data:
  graph-url: https://data.example.com/0.9.0/maps-earth-planet-v1.241202/LosAngeles.graph.obj.zst
  router-config-json: ""

