apiVersion: v1
kind: ConfigMap
metadata:
  name: otp-sfbayarea-config
data:
  graph-url: https://data.example.com/0.12.0/maps-earth-planet-v1.260727/SfBayArea.graph.obj.zst
  otp-config-json: |
    {}
  router-config-json: |
    {
      "updaters": [
        {
          "feedId": "headway-53",
          "type": "stop-time-updater",
          "frequency": "60s",
          "url": "https://api.bart.gov/gtfsrt/tripupdate.aspx"
        },
        {
          "feedId": "headway-53",
          "type": "real-time-alerts",
          "frequency": "300s",
          "url": "https://api.bart.gov/gtfsrt/alerts.aspx"
        }
      ]
    }

