apiVersion: v1
kind: ConfigMap
metadata:
  name: otp-puget-sound-config
data:
  graph-url: https://data.example.com/0.12.0/maps-earth-planet-v1.260727/transit/maps-earth-planet-v1.260727-puget-sound-2026-08-14.graph.obj.zst
  router-config-json: |
    {
      "updaters": [
        {
          "feedId": "headway-1080",
          "type": "stop-time-updater",
          "frequency": "60s",
          "url": "https://s3.amazonaws.com/kcm-alerts-realtime-prod/tripupdates.pb"
        },
        {
          "feedId": "headway-1080",
          "type": "real-time-alerts",
          "frequency": "300s",
          "url": "https://s3.amazonaws.com/kcm-alerts-realtime-prod/alerts.pb"
        }
      ]
    }

