apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-sf-bay-area
spec:
  selector:
    matchLabels:
      app: opentripplanner-sf-bay-area
  replicas: 1
  template:
    metadata:
      labels:
        app: opentripplanner-sf-bay-area
    spec:
      initContainers:
        - name: init
          image: ghcr.io/headwaymaps/opentripplanner-init:maps-earth-dev
          imagePullPolicy: Always
          volumeMounts:
            - name: opentripplanner-volume
              mountPath: /data
          env:
            - name: OTP_ARTIFACT_URL
              value: "https://data.example.com/0.12.0/maps-earth-planet-v1.260817/transit/maps-earth-planet-v1.260817-sf-bay-area-graph-2026-08-29-2f919753.obj.zst"
            - name: OTP_ROUTER_CONFIG_JSON
              value: |
                {
                  "updaters": [
                    {
                      "feedId": "headway-53",
                      "type": "stop-time-updater",
                      "frequency": "60s",
                      "url": "https://api.bart.gov/gtfsrt/tripupdate.aspx"
                    },
                    {
                      "feedId": "headway-53",
                      "type": "real-time-alerts",
                      "frequency": "300s",
                      "url": "https://api.bart.gov/gtfsrt/alerts.aspx"
                    }
                  ]
                }
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 128Mi
      containers:
        - name: main
          image: ghcr.io/headwaymaps/opentripplanner:maps-earth-dev
          env:
            - name: "JAVA_OPTS"
              # keep this in sync to be just under the resources.limits.memory
              value: "-Xmx5G"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: opentripplanner-volume
              mountPath: /var/opentripplanner
          resources:
            limits:
              # keep this in sync to be just above env.JAVA_OPTS.-Xmx
              memory: 5.25Gi
            requests:
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 20
      volumes:
        - name: opentripplanner-volume
          persistentVolumeClaim:
            claimName: opentripplanner-sf-bay-area-maps-earth-planet-v1-260817-0-12-0-2026-08-29-6b51fe47
