apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentripplanner-sf-bay-area-maps-earth-planet-v1-260727-0-12-0-2026-08-14
  labels:
    app.kubernetes.io/part-of: headway
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
