apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentripplanner-puget-sound-maps-earth-planet-v1-260817-0-12-0-2026-09-03-20034558
  labels:
    app.kubernetes.io/part-of: headway
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
