apiVersion: apps/v1
kind: Deployment
metadata:
  name: tileserver
spec:
  selector:
    matchLabels:
      app: tileserver
  replicas: 1
  template:
    metadata:
      labels:
        app: tileserver
    spec:
      initContainers:
        - name: init
          image: ghcr.io/headwaymaps/tileserver-init:maps-earth-dev
          imagePullPolicy: Always
          volumeMounts:
            - name: tileserver-volume
              mountPath: /data
          env:
            - name: TERRAIN_ARTIFACT_SOURCE
              value: "https://data.example.com/0.12.0/terrain-2026-08-26-d961012b.mbtiles"
            - name: TERRAIN_ARTIFACT_DEST
              value: /data/tiles/terrain.mbtiles
            - name: LANDCOVER_ARTIFACT_SOURCE
              value: "https://data.example.com/0.12.0/landcover-2026-08-26-af6aa17e.mbtiles"
            - name: LANDCOVER_ARTIFACT_DEST
              value: /data/tiles/landcover.mbtiles
            - name: AREAMAP_ARTIFACT_SOURCE
              value: "https://data.example.com/0.12.0/maps-earth-planet-v1.260817/maps-earth-planet-v1.260817-2026-08-26-3121d137.pmtiles"
            - name: AREAMAP_ARTIFACT_DEST
              value: /data/tiles/areamap.pmtiles
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 100Mi
      containers:
        - name: tileserver
          image: ghcr.io/headwaymaps/tileserver:maps-earth-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: tileserver-volume
              mountPath: /data
          env:
            - name: PORT
              value: "8000"
          resources:
            limits:
              memory: 1500Mi
            requests:
              memory: 250Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 10
      volumes:
        - name: tileserver-volume
          persistentVolumeClaim:
            claimName: tileserver-maps-earth-planet-v1-260817-0-12-0-2026-08-26-6d731f54
