apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valhalla-maps-earth-planet-v1-260817-0-12-0-2026-08-26-e058dc54
  labels:
    app.kubernetes.io/part-of: headway
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 200Gi
