apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-config
data:
  area: maps-earth-planet-v1.28
  public-url: https://maps.earth
  bbox: ""
  enable-transit-routing: "1"
  natural-earth-source-url: https://data.example.com/0.6.0/natural_earth.mbtiles
  mbtiles-source-url: https://data.example.com/0.6.0/maps-earth-planet-v1.28/maps-earth-planet-v1.28.mbtiles
  valhalla-artifact-url: https://data.example.com/0.6.0/maps-earth-planet-v1.28/maps-earth-planet-v1.28.valhalla.tar.zst
  placeholder-artifact-url: https://data.example.com/0.6.0/maps-earth-planet-v1.28/maps-earth-planet-v1.28.placeholder.tar.zst
  elasticsearch-artifact-url: https://data.example.com/0.6.0/maps-earth-planet-v1.28/maps-earth-planet-v1.28.elasticsearch.tar.zst
  pelias-config-json: |
    {
      "logger": {
        "level": "info",
        "timestamp": false
      },
      "esclient": {
        "nodes": [ "http://pelias-elasticsearch:9200" ]
      },
      "elasticsearch": {
        "settings": {
          "index": {
            "refresh_interval": "10s",
            "number_of_replicas": "0",
            "number_of_shards": "5"
          }
        }
      },
      "api": {
        "services": {
          "placeholder": { "url": "http://pelias-placeholder:4100" },
          "libpostal": { "url": "http://pelias-libpostal:4400" },
          "pip": { "url": "http://pelias-pip:4400" }
        }
      },
      "imports": {
        "adminLookup": {
          "enabled": true
        },
        "openstreetmap": {
          "leveldbpath": "/tmp",
          "datapath": "/data/openstreetmap",
          "import": [{
            "filename": "data.osm.pbf"
          }]
        },
        "whosonfirst": {
          "datapath": "/data/whosonfirst",
          "importPostalcodes": true
        },
        "polyline": {
          "datapath": "/data/polylines",
          "files": [ "extract.0sv" ]
        }
      }
    }
