apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentripplanner-losangeles-maps-earth-planet-v1-260420-0-11-0
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
