apiVersion: v1
kind: ConfigMap
metadata:
  name: otp-los-angeles-config
data:
  graph-url: https://data.example.com/0.12.0/maps-earth-planet-v1.260727/transit/maps-earth-planet-v1.260727-los-angeles-2026-08-14.graph.obj.zst
  router-config-json: ""

