apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentripplanner-los-angeles-maps-earth-planet-v1-260727-0-12-0-2026-08-14
  labels:
    app.kubernetes.io/part-of: headway
    headway/area-tag: maps-earth-planet-v1-260727
    headway/data-tag: 0-12-0
    headway/graph-date: "2026-08-14"
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
