apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-maps-earth-planet-v1-260817-0-12-0-2026-08-26-86f31e2b
  labels:
    app.kubernetes.io/part-of: headway
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 90Gi
