apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: placeholder-maps-earth-planet-v1-260727-0-12-0
  labels:
    app.kubernetes.io/part-of: headway
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 40Gi
