pmtiles:
  sources:
    areamap: ../../data/Bogota/Bogota.pmtiles
mbtiles:
  sources:
    landcover: ../../data/Bogota/landcover.mbtiles
    terrain: ../../data/Bogota/terrain.mbtiles
styles:
  paths: ['./assets/styles']
sprites:
  paths: ['./assets/sprites']
fonts:
  paths: ['./assets/fonts']
