base_path: "/tileserver"
cache_size_mb: 1024
pmtiles:
  sources:
    areamap-mlt:
      path: "${DATA_PATH}/Bogota/Bogota.pmtiles"
      output_format: mlt
      convert_to_mlt:
        allow_shared_dict: false
        allow_fastpfor: false
    areamap-mvt:
      path: "${DATA_PATH}/Bogota/Bogota.pmtiles"
      output_format: mvt
mbtiles:
  sources:
    landcover: "${DATA_PATH}/Bogota/landcover.mbtiles"
    terrain: "${DATA_PATH}/Bogota/terrain.mbtiles"
styles:
  paths: ['./assets/styles']
sprites:
  paths: ['./assets/sprites']
fonts:
  paths: ['./assets/fonts']
