pmtiles:
  sources:
    areamap: /data/tiles/areamap.pmtiles
mbtiles:
  sources:
    landcover: /data/tiles/landcover.mbtiles
    terrain: /data/tiles/terrain.mbtiles
styles:
  paths: ['/app/assets/styles']
sprites:
  paths: ['/app/assets/sprites']
fonts:
  paths: ['/app/assets/fonts']
