[package]
name = "gtfout"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.6.6", features = ["derive"] }
csv = "1.4.0"
geo = { version = "0.33.1", features = ["serde"] }
geopackage = { version = "0.9.1", features = ["bundled"] }
log = "0.4.34"
pretty_env_logger = "0.5.0"
reqwest = { version = "0.13.4", default-features = false, features = ["blocking", "rustls", "http2", "query"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
zip = "8.6.0"
