[package]
name = "gtfout"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { workspace = true }
csv = "1.4.0"
geo = { workspace = true, features = ["serde"] }
geopackage = { version = "0.9.1", features = ["bundled"] }
log = { workspace = true }
pretty_env_logger = "0.5.0"
reqwest = { version = "0.13.4", default-features = false, features = ["blocking", "rustls", "http2", "query"] }
serde = { workspace = true }
serde_json = { workspace = true }
zip = "8.6.0"
