apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: placeholder-seattle-latest-dev-2026-08-20-70d1b581
  labels:
    app.kubernetes.io/part-of: headway
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 40Gi
