apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valhalla-seattle-latest-dev-2026-08-19-446e7af3
  labels:
    app.kubernetes.io/part-of: headway
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 200Gi
