apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentripplanner-sf-bay-area-maps-earth-planet-v1-260817-0-13-0-2026-09-17-4543ce30
  labels:
    app.kubernetes.io/part-of: headway
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
