//! Rust bindings for OTP's GTFS GraphQL schema.
//!
//! The `schema` module is generated by cynic from `schemas/otp.graphql` (see `build.rs`). The
//! query structs in [`crate::otp::gtfs_graphql`] and [`crate::otp::otp_router`] are checked
//! against it at compile time: a field, argument, or nullability that doesn't match the schema is
//! a build error rather than a puzzling runtime response.
//!
//! Custom scalars have no inherent Rust representation, so we choose one for each of the scalars
//! we use. Anything not mapped here can't be selected in a query.

#[cynic::schema("otp")]
mod generated {}

pub use generated::*;

// RFC 3339, e.g. "2024-05-17T10:00:00-07:00". `chrono`'s (de)serialization is already RFC 3339.
cynic::impl_scalar!(
    chrono::DateTime<chrono::FixedOffset>,
    generated::OffsetDateTime
);
// A 64 bit integer, used by OTP for durations in seconds and Unix timestamps.
cynic::impl_scalar!(i64, generated::Long);

// `impl_scalar!` would also implement `Variable` for these, which cynic already implements for
// `f64`/`String` as the built-in `Float`/`String` scalars. We only ever use them for output
// fields and input object fields, neither of which needs `Variable`.
macro_rules! impl_scalar_output_only {
    ($type:ty, $schema_type:ty) => {
        impl cynic::schema::IsScalar<$schema_type> for $type {
            type SchemaType = $schema_type;
        }
        impl cynic::coercions::CoercesTo<$schema_type> for $type {}
    };
}

// A WGS84 latitude or longitude.
impl_scalar_output_only!(f64, generated::CoordinateValue);
// An encoded polyline: https://developers.google.com/maps/documentation/utilities/polylinealgorithm
impl_scalar_output_only!(String, generated::Polyline);
