apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-seattle
spec:
  selector:
    matchLabels:
      app: opentripplanner-seattle
  replicas: 1
  template:
    metadata:
      labels:
        app: opentripplanner-seattle
    spec:
      initContainers:
        - name: init
          image: ghcr.io/headwaymaps/opentripplanner-init:maps-earth-dev
          imagePullPolicy: Always
          volumeMounts:
            - name: opentripplanner-volume
              mountPath: /data
          env:
            - name: OTP_ARTIFACT_URL
              value: "https://data.example.com/dev/seattle-latest/transit/Seattle-seattle-graph-2026-08-20-a1b4fe0b.obj.zst"
            - name: OTP_ROUTER_CONFIG_JSON
              value: |
                {
                  "updaters": [
                    {
                      "feedId": "headway-1330",
                      "type": "stop-time-updater",
                      "frequencySec": 60,
                      "url": "https://s3.amazonaws.com/kcm-alerts-realtime-prod/tripupdates.pb"
                    },
                    {
                      "feedId": "headway-1330",
                      "type": "real-time-alerts",
                      "frequencySec": 300,
                      "url": "https://s3.amazonaws.com/kcm-alerts-realtime-prod/alerts.pb"
                    }
                  ]
                }
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 128Mi
      containers:
        - name: main
          image: ghcr.io/headwaymaps/opentripplanner:maps-earth-dev
          env:
            - name: "JAVA_OPTS"
              # keep this in sync to be just under the resources.limits.memory
              value: "-Xmx5G"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: opentripplanner-volume
              mountPath: /var/opentripplanner
          resources:
            limits:
              # keep this in sync to be just above env.JAVA_OPTS.-Xmx
              memory: 5.25Gi
            requests:
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 20
      volumes:
        - name: opentripplanner-volume
          persistentVolumeClaim:
            claimName: opentripplanner-seattle-seattle-latest-dev-2026-08-20-f21ba60d
