apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tileserver-seattle-latest-dev
  labels:
    app.kubernetes.io/part-of: headway
    headway/area-tag: seattle-latest
    headway/data-tag: dev
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 200Gi
