apiVersion: apps/v1
kind: Deployment
metadata:
  name: valhalla
spec:
  selector:
    matchLabels:
      app: valhalla
  replicas: 1
  template:
    metadata:
      labels:
        app: valhalla
    spec:
      initContainers:
        - name: init
          image: ghcr.io/headwaymaps/valhalla-init:maps-earth-dev
          imagePullPolicy: Always
          volumeMounts:
            - name: valhalla-volume
              mountPath: /data
          env:
            - name: VALHALLA_ARTIFACT_URL
              value: "https://data.example.com/dev/seattle-latest/Seattle-valhalla-2026-08-19-cf37274b.tar.zst"
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
      containers:
        - name: main
          image: ghcr.io/headwaymaps/valhalla:maps-earth-dev
          imagePullPolicy: Always
          ports:
          - containerPort: 8002
          volumeMounts:
          - name: valhalla-volume
            mountPath: /data
          resources:
            limits:
              memory: 8Gi
            requests:
              memory: 250Mi
      volumes:
        - name: valhalla-volume
          persistentVolumeClaim:
            claimName: valhalla-seattle-latest-dev-2026-08-19-446e7af3
