name: Push `latest` containers

on:
  push:
    tags:
      - 'v*'

jobs:
  build-latest:
    name: Push latest images to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          # pinning to `latest` requires using the GH API, which causes spurious rate limiting errors
          version: "0.7.1"
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u headwaymaps --password-stdin
      - name: Earthly version check
        run: earthly --version
      - name: Push latest images
        run: earthly --use-inline-cache --save-inline-cache --push +images --tags "latest ${{ github.ref_name }}"
      - name: Push latest branded images
        run: earthly --use-inline-cache --push +images --branding=maps.earth --tags "maps-earth-latest maps-earth-${{ github.ref_name }}"

